sudo: required

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - docker build -t test_build .
  - docker run test_build python3 /usr/src/ff_bot/setup.py test

env:
  - BOT_ID=0 LEAGUE_ID=0
