NOUNS = [
"Amateur",
"Animal",
"Anorak",
"Ape",
"Apefucker",
"Arse",
"Arse-licker",
"Arsebreath",
"Arsecunt",
"Arseface",
"Arsehole",
"Ass",
"Ass-kisser",
"Ass-nugget",
"Ass clown",
"Asscunt",
"Assface",
"Asshat",
"Asshole",
"Assmonkey",
"Asswagon",
"Assweed",
"Asswipe",
"Aunt fucker",
"Baby",
"Backwoodsman",
"Badass",
"Badgerfucker",
"Bag of dicks",
"Bandit",
"Bangsat",
"Barbarian",
"Bastard",
"Beast",
"Beetlehead",
"Beginner",
"Beldame",
"Bell-end",
"Berk",
"Bespawler",
"Bimbo",
"Birdbrain",
"Bitch",
"Bitchface",
"Bitchwad",
"Bitchzilla",
"Blackguard",
"Blaggard",
"Blockhead",
"Blubber gut",
"Bluntie",
"Bogeyman",
"Bonehead",
"Booby",
"Bootlicker",
"Boozer",
"Boyfucker",
"Bozo",
"Brotherfucker",
"Buffoon",
"Bugger",
"Bum",
"Bum-fucker",
"Bum chum",
"Burden",
"Buttfucker",
"Butthead",
"Butthole",
"Buttlicker",
"Caveman",
"Chauvinist",
"Chav",
"Cheater",
"Chicken",
"Chickenfucker",
"Childfucker",
"Chump",
"Churl",
"Clown",
"Cock",
"Cockboy",
"Cockfucker",
"Cockhead",
"Cockholster",
"Cockmaster",
"Cockroach",
"Cocksucker",
"Cockwomble",
"Con man",
"Con merchant",
"Cougar",
"Country bumpkin",
"Cousinfucker",
"Cow",
"Crack whore",
"Craphole",
"Creep",
"Cretin",
"Crook",
"Cumstain",
"Cunt",
"Cunt fart",
"Cuntass",
"Cuntbitch",
"Cuntlicker",
"Cuntsucker",
"Cuntzilla",
"Daughterfucker",
"Deadhead",
"Degenerate",
"Der-brain",
"Desperado",
"Devil",
"Dick",
"Dick-licker",
"Dickbag",
"Dickface",
"Dickfucker",
"Dickhead",
"Dicktard",
"Dimwit",
"Dinosaur",
"Dirtbag",
"Dirthead",
"Dodo",
"Dog",
"Dogfucker",
"Dolt",
"Donkey",
"Donkeyfucker",
"Doofus",
"Dope",
"Dotterel",
"Douche",
"Douche bag",
"Douchefag",
"Douchelord",
"Dracula",
"Dreamer",
"Drunkard",
"Duckfucker",
"Dumbass",
"Dumbbell",
"Dumbo",
"Dummy",
"Dunce",
"Earthworm",
"Edgelord",
"Egotist",
"Envirotard",
"Eunuch",
"Faggot",
"Fagtard",
"Fagtits",
"Farmer",
"Fart",
"Fatso",
"Fellow",
"Fibber",
"Fink",
"Fish",
"Fishwife",
"Fixer",
"Flake",
"Fool",
"Freak",
"Fruitcake",
"Fuck",
"Fuck noggin",
"Fuck nugget",
"Fuckbait",
"Fuckbucket",
"Fucker",
"Fuckhead",
"Fucklord",
"Fucktard",
"Fucktoy",
"Fuckweasel",
"Fugly",
"Gawk",
"Geebag",
"Git",
"Gold digger",
"Goof",
"Goon",
"Goose",
"Gorilla",
"Greeniac",
"Grouch",
"Grumpy",
"Helldog",
"Hilding",
"Hillbilly",
"Hippie",
"Ho",
"Hoe",
"Homo",
"Hooligan",
"Horse's ass",
"Horse's necktie",
"Horsefucker",
"Hosebag",
"Hypocrite",
"Idiot",
"Idiotist",
"Ignoramus",
"Imbecile",
"Inbred",
"Intercourser",
"Jackass",
"Jackwagon",
"Jelly",
"Jerk",
"Joker",
"Junkie",
"Keyboard warrior",
"Lamebrain",
"Landwhale",
"Lard face",
"Liar",
"Loser",
"Low-life",
"Lunatic",
"Lunkhead",
"Lurdane",
"Mackerel",
"Madman",
"Mamzer",
"Megabitch",
"Megadouche",
"Minx",
"Missing link",
"Monkey",
"Monster",
"Moron",
"Motherfucker",
"Mucky pup",
"Mutant",
"Mutt",
"Ne'er-do-well",
"Neanderthal",
"Neckbeard",
"Nerd",
"Nerf herder",
"Nimrod",
"Nincompoop",
"Ninny",
"Nitwit",
"Nobody",
"Nonce",
"Noodle",
"Numbnuts",
"Numbskull",
"Numskull",
"Oaf",
"Oddball",
"Ogre",
"Outlaw",
"Oxygen Thief",
"Pack",
"Pain in the ass",
"Peasant",
"Pencil dick",
"Pervert",
"Pig",
"Pigfucker",
"Piggy-wiggy",
"Pillock",
"Pinhead",
"Pirate",
"Pissface",
"Porno freak",
"Prick",
"Pseudo-intellectual",
"Puppet",
"Pussyfucker",
"Quack",
"Quat",
"Queer",
"Querulant",
"Rat",
"Rat-fink",
"Ratcatcher",
"Ratfink",
"Redneck",
"Reject",
"Retard",
"Riff-raff",
"Roaster",
"Robot",
"Rowdy",
"Rudesby",
"Ruffian",
"Sadist",
"Saprophyte",
"Sausage-masseuse",
"Scumbag",
"Scumhead",
"Scumlord",
"Scuzzbag",
"Sewer rat",
"Shark",
"Sheepfucker",
"Sheepshagger",
"Shit-eater",
"Shit stain",
"Shitass",
"Shitbucket",
"Shitehawk",
"Shithead",
"Shitneck",
"Shitnugget",
"Shitsack",
"Shitter",
"Shitweasel",
"Shyster",
"Simpleton",
"Skullfucker",
"Skunk",
"Skunkfucker",
"Slag",
"Slave",
"Sleeze",
"Sleeze bag",
"Slob",
"Slutfucker",
"Snail",
"Snake",
"Snob",
"Snot",
"Snotball",
"Snowflake",
"Son of a bitch",
"Son of a motherless goat",
"Son of a whore",
"Sphincter",
"Square",
"Stinker",
"Stinkhole",
"Swindler",
"Swine",
"Sycophant",
"Thief",
"Thundercunt",
"Toad",
"Tree hugger",
"Troll",
"Trollface",
"Turd",
"Turdball",
"Twat",
"Twatwaffle",
"Twerp",
"Twit",
"Twunt",
"Unclefucker",
"Vampire",
"Vandal",
"Varmint",
"Vermin",
"Wacko",
"Wallflower",
"Wank stain",
"Wanker",
"Weeze Bag",
"Weirdo",
"Whore",
"Whorefucker",
"Whoreson",
"Windfucker",
"Windsucker",
"Wino",
"Witch",
"Womanizer",
"Worm",
"Wretch",
"Xenophobe",
"Yahoo",
"Yes-man",
"Zitface",
"adult",
"royal highness",
"dish",
"brooder",
"social butterfly",
"girl next door",
"bimbo",
"old soul",
"gal",
"man eater",
"wild woman",
"dynamo",
"gentle soul",
"kept woman",
"feminist",
"gentlewoman",
"daydreamer",
"philanthropist",
"introvert",
"queen bee",
"whore",
"parent",
"thinker",
"sister",
"survivor",
"connoisseur",
"huntress",
"child",
"leader",
"winch",
"queen",
"enemy",
"achiever",
"woman of means",
"hard worker",
"Miss",
"angel",
"risk-taker",
"girlfriend",
"wild one",
"nurturer",
"belle of the ball",
"young girl",
"escort",
"dreamer",
"lass",
"fashion-plate",
"coquette",
"spouse",
"goddess",
"keeper",
"hottie",
"cat",
"maiden",
"matron",
"therapist",
"catch",
"mystery",
"tramp",
"widow",
"dame",
"enthusiast",
"married woman",
"redhead",
"leading lady",
"dream girl",
"woman of her word",
"man killer",
"fashionista",
"damsel",
"planner",
"spinster",
"blond",
"siren",
"young lady",
"lover",
"beauty queen",
"communicator",
"drama queen",
"superstar",
"individual",
"daughter",
"object of desire",
"advocate",
"go-getter",
"heiress",
"sweetie",
"squaw",
"coordinator",
"heartbreaker",
"beauty",
"mademoiselle",
"companion",
"girl",
"artist",
"knockout",
"grandmother",
"friend",
"person",
"enchantress",
"kindred spirit",
"witch",
"snuggler",
"inspiration",
"nag",
"protector",
"good looks",
"lady",
"minx",
"mommy",
"party girl",
"optimist",
"young woman",
"chick",
"intellectual",
"life coach",
"student",
"bookworm",
"personality",
"healer",
"babe",
"comedian",
"fireball",
"cheater",
"skirt",
"saint",
"sweetheart",
"adventurer",
"provoker",
"aunt",
"soul",
"teacher",
"she",
"people person",
"broad",
"showoff",
"nymph",
"busybody",
"wealthy",
"hypocrite",
"rebel",
"girly girl",
"darling",
"confidante",
"character",
"fighter",
"manipulator",
"stunner",
"idealist",
"lady friend",
"femme fatale",
"working girl",
"woman about town",
"caretaker",
"superwoman",
"seductress",
"hostess",
"bride-to-be",
"heroine",
"athlete",
"Ms.",
"woman",
"caregiver",
"cutie pie",
"sex symbol",
"natural beauty",
"ma’am",
"belle",
"she-devil",
"temptress",
"patron",
"mistress",
"mother",
"lioness",
"fox",
"hag",
"expert",
"brunette",
"peacekeeper",
"bitch",
"floozy",
"actress",
"lassie",
"perfectionist",
"tomboy",
"diva",
"realist",
"princess",
"madam",
"vamp",
"wife",
"activist",
"best friend",
"martyr",
"vixen",
"kind soul",
"loner",
"flirt",
"extrovert",
"supporter",
"teenager",
"provider",
"mom",
"sportswoman",
"cover girl",
"creature",
"doll",
"Immoral Assholes",
"Sickening Outlaw",
"Beat It",
"Injurious Bitch",
"Obscene Dick",
"Horrifying Dickhead",
"Vile Douche",
"Nocuous Douchebag",
"Abominable Fool",
"Nasty Idiot",
"Harmful Jerk",
"Swinish Loser",
"Detestable Ass",
"Horrible Boob",
"Sinful Buffoon",
"Rotten Clown",
"Offensive Idiot",
"Abhorrent Jerk",
"Execrable Moron",
"Unworthy Nerd",
"Shocking Nitwit",
"Disturbing Stooge",
"Evil Sucker",
"Malevolent Twit",
"Reprehensible Birdbrain",
"Vicious Blockhead",
"Lousy Bonehead",
"Nefarious Bore",
"Unpleasant Clod",
"Dreadful Cretin",
"Iniquitous Dimwit",
"Barbaric Dolt",
"Reprobate Dope",
"Disagreeable Dunce",
"Horrific Dunderhead",
"Abject Fathead",
"Scandalous Goose",
"Heinous Ignoramus",
"Infamous Illiterate",
"Worthless Imbecile",
"Contemptible Innocent",
"Dismaying Lightweight",
"Wicked Maroon",
"Degenerate Truant",
"Revolting Escapee",
"Pejorative Escaper",
"Repellent No-Show",
"Disheartening Refugee",
"Noisome Runaway",
"Vexatious Shirker",
"Repugnant Slacker",
"Awful Traitor",
"Wretched Apostate",
"Horrid Betrayer",
"Cursed Criminal",
"Displeasing Defector",
"Flagrant Derelict",
"Base Recreant",
"Inclement Renegade",
"Ignominious Absconder",
"Despicable Backslider",
"Egregious Delinquent",
"Fiendish Lawbreaker",
"Odious Loon",
"Ignoble Nincompoop",
"Infernal Ninny",
"Horrendous Numskull",
"Hideous Oaf",
"Woeful Sap",
"Hateful Schlemiel",
"Calamitous Silly",
"Diabolical Simpleton",
"Hellish Twerp",
"Dire Victim",
"Unpalatable Ox",
"Galling Prick",
"Loathsome Pussy",
"Repulsive Shit",
"Ghastly Slut",
"Sordid Dumb Ass",
"Treacherous Ass",
"Ruinous Jackass",
"Atrocious Prick",
"Deleterious Cocksucker",
"Villainous Dickhead",
"Foul Motherfucker",
"Appalling Shit",
"Terrible Son Of A Bitch",
"Noxious Asshat",
"Nauseating Asswipe",
"Monstrous Idiot",
"Grievous Jerk",
"Icky Pig",
"Mischievous Idiot",
"Detrimental Schmuck",
"Sinister Asshole",
"Beastly Black Sheep",
"Distasteful Derelict",
"Annoying Wino",
"Disgusting Jerk",
"nappropriate big jerk",
"run-and-gun bully",
"dead lettuce",
"snuggly screw-up",
"joyful jealousy",
"cold-hearted eskimo",
"ribbed antidepressant drug",
"sexy musical chairs",
"peaceful shame",
"professional tire iron",
"fuel-efficient litter pan",
"evil stir stick",
"vintage dream-crusher",
"heartbreaking stick figure",
"stumpy idea he suggested",
"ready-for-action conscience",
"limp striped hyena",
"waist-slimming reproach",
"four-wheel drive snake-in-the-grass",
"lousy incident",
"sneaky nudist camp",
"vibrant chauvinist",
"portly no sense of humor",
"sporty friendly grandma",
"crazy revenge",
"supportive fake",
"no-good lettuce",
"full of rage fraud",
"shady dog",
"polished ice cream",
"missing multi-billionaire",
"smooth monster",
"dumpy sealed off tomb",
"performance-inspired broken promises",
"overweight basket case",
"sculpted hiking boots",
"frightening smell",
"slip-on puppy",
"distended mistake",
"frightful control account",
"willing place of business",
"easy-to-train villain",
"tubby falseness",
"spectacular shivering toes",
"watchful floozy",
"undersized wiley coyote",
"superior manure",
"bone-chilling legal warrant",
"hard-hitting stick figure",
"bottle-conditioned trainer",
"gloomy promise-breaker",
"mixed breed physical abuse",
"crappy lack of morality",
"full-bodied preventive strike",
"wear-anywhere moron",
"ultimate dog poop",
"keepsake machete",
"fang-tastic hunting ground",
"far away jackass",
"pale skull and crossbones",
"cheap natural history",
"stylish knight’s service",
"limber hiking companion",
"creamy dummy",
"grouchy remnant of chaos",
"textured good-for-nothing",
"humiliating big jerk",
"long distance patrolman",
"large sphere of influence",
"together again dingle berry",
"state-of-the-art catastrophe",
"wild ass",
"nimble indiscriminate killer",
"limited towelette",
"distressed useless brakes",
"easy-to-play excuse",
"new nature trail",
"good wagging tail",
"terrifying bored child",
"heartwarming enemy",
"family-owned fluffy slippers",
"crazed master",
"cheeky keepsake machete",
"unhappy light bulb",
"narrow-minded pancake",
"supernatural son-of-a-bitch",
"comforting grouch",
"asymmetrical brethren",
"relaxed final word",
"willowy weasel",
"full-flavored lack of trust",
"quilted phonograph record",
"pissed off indirect expression",
"spiteful fluffy slippers",
"intellectual rocket science",
"chunky drug addict",
"noble pile of decomposition",
"sluggish rocket science",
"decorative physical abuse",
"affectionate thief",
"wagging untruth",
"racist disservice",
"cheerful toilet seat",
"fluffy poser",
"intuitive pig",
"boring heartbreak",
"strategizing punk",
"memorable pizza cutter",
"family-friendly extremity",
"enormous toast",
"self-entitled lips",
"heartfelt informal request",
"freshly brewed meanie",
"supersoft lunatic",
"stacked bullshit",
"perfectly balanced dick",
"sharp general knowledge",
"sympathetic mediation",
"at-the-ready fluff ball",
"timeless towelette",
"strong suckling pig",
"contemporary queen",
"content dirtbag",
"flat-chested man of my dreams",
"structural catastrophe",
"hoppy liquid oxygen",
"spectacular brat",
"twisted snake-in-the-grass",
"manual background story",
"long-legged whore",
"hateful life raft",
"easy-to-drive schmuck",
"common toilet seat",
"offensive son-of-a-bitch",
"backstabbing misfortune",
"visual shell of a person",
"drunk planetary house",
"corrupt broken promises",
"playful bully",
"magical blunder",
"naturally show off",
"silky soft loser",
"expensive shoe string",
"bitchy peace offering",
"strange kitty cat",
"tiny-dick behavior",
"haunting musical chairs",
"organic microwaved eggs",
"brainless ways of world",
"everlasting railroad worm",
"plus size self-condemnation",
"half-priced mathematics department",
"ominous gothic romance",
"stout insult",
"high-performance weasel",
"approachable prick",
"leggy fact that I don’t think",
"loose general knowledge",
"confrontational freak",
"wretched sealed off tomb",
"sweet thunder legs",
"pleasant napper",
"sadistic manipulator",
"fully lined suckling pig",
"refreshing tank",
"trustworthy backstabber",
"elephantine pig",
"eccentric coffee pot",
"startled vengeance",
"pathetic liquid oxygen",
"straight phony",
"quick-shifting jet ski",
"huge positive feedback",
"curvy bouncy ball",
"crawly mistake",
"bull-headed lover",
"out-of-control nightmare",
"soft theft",
"insane volcanic crater",
"tactical stir stick",
"irrational gold-digger",
"bad striped hyena",
"sawed-off scumbag",
"sleazy abnormal behavior",
"well-trained lack of morality",
"unpredictable messiness",
"distinctive injury",
"dimpled sheep dip",
"haunted trust",
"housebroken theft",
"double-crossing storm",
"considerate louse",
"queenly stupidity",
"dapper misery",
"hand-washed love of her life",
"synthetic accident",
"bright-eyed double fault",
"pea-brained waste of a person",
"submissive wiener",
"bottled sweet tailpipe",
"mixed-media princess",
"quick dingle berry",
"protective telephone",
"legendary falseness",
"micro-brewed revenge",
"wrong constant reminder",
"remodeled orbital plane",
"craft-brewed police squad",
"intoxicating nut job",
"functional tentacle",
"ill-tempered modern times",
"kingly wild sheep",
"narrative mutt",
"unique president of the night",
"deceitful lapdog",
"brewery-fresh sleazeball",
"waterproof deceit",
"shiny sorrow",
"spindly lies",
"encouraging main people",
"colored snuggle bug",
"developed wanker",
"occult travel guidebook",
"rude jungle psychology",
"reprehensible deer antler",
"thoughtless cheater",
"flawed new version",
"terrible man-whore",
"busty descending color",
"odor-absorbing remnant of chaos",
"lightning-fast cheater",
"fun freeloader",
"unacceptable fake",
"stretch serious question",
"generous patience",
"yarn-dyed mimicker",
"big-bellied bad mood",
"creepy dirty coffee cup",
"unreliable litter pan",
"tender whole blood",
"odor-resistant slimeball",
"sturdy idiot",
"long-limbed weed wacker",
"well-packaged ego",
"lonely candlestick maker",
"cushioned nibblets",
"reinforced microwaved eggs",
"special disgust",
"narrow unit of unholy depth",
"glamorous corn cake",
"neverending friendly claim",
"single-player scumbucket",
"custom-built abnormal behavior",
"dirty wild, wild sheep",
"crate-trained mood",
"instinctual dumbass",
"kid-friendly mimicker",
"opaque feelings",
"dressed-up useless brakes",
"scientific king",
"outraged fool",
"family-oriented sweet tailpipe",
"underhanded nudist camp",
"favorite indirect expression",
"critically acclaimed serious question",
"irresponsible pal",
"proprietary outside dog",
"lush notion of love",
"slinky mediation",
"tasteless jungle psychology",
"obsessive-compulsive lack of trust",
"heinous grouchiness",
"ridiculous toilet",
"front-wheel drive gaming laptop",
"stiff troublemaker",
"measly planetary house",
"eco-friendly disgrace",
"trendsetting grouchiness",
"women’s tentacle",
"lean monkey",
"relaxing damage",
"award-winning people who are hurt",
"rescued stress reliever",
"pissed sheep dip",
"mistaken mood",
"unforgettable skinny woman",
"strapless nut job",
"colossal love of her life",
"sweating brainchild",
"chilled good-for-nothing",
"best failure",
"meaningful clan member",
"empathetic volcanic crater",
"moisture-wicking frustration",
"abstract preventive strike",
"up-to-no-good hurt",
"discounted hurt",
"maniacal regret",
"hybrid grouch",
"happy skull and crossbones",
"defined hissy fit",
"energetic fluffy clouds",
"anatomically designed life companion",
"self-centered boner",
"quintessential monkey",
"top-heavy overlord",
"sure-footed temperament",
"willing-to-learn pillow",
"eager-to-please nightmare",
"defiant space emulator",
"chauvinistic pup",
"silly really tough guy",
"deceased lack of judgement",
"jolly mad cow disease",
"full-grown baby",
"paunchy frustration",
"dying talker",
"cocky matrimonial law",
"progressive regretfulness",
"elastic pile of decomposition",
"dynamic electric furnace",
"grumpy joke of a person",
"loitering second chance",
"entertaining intention",
"top-of-the-line bonehead",
"friendly overlord",
"thirst-quenching backstabber",
"interesting ship’s captain",
"symmetrical baby",
"flexible bullshit",
"imported wandering eye",
"thick twinkling uncleanness",
"lively mad-dog skullcap",
"macro-brewed knight’s service",
"swindling basket case",
"caught red-handed pistol",
"touching wrinkle",
"wee problem solver",
"cask-conditioned freak",
"mighty bad judgment",
"crushing dickhead",
"staked manipulator",
"real-time fuzz ball",
"violent friendly claim",
"short-haired selfishness",
"complex guilt",
"slender liar",
"driving rough-skinned newt",
"quick-to-set-up kook",
"athletic baptist church",
"laidback disappointment",
"fuzzy travel guidebook",
"skinny-fit hunting dog",
"agreeable scourge upon the earth",
"manipulative quirk",
"stretchy anger",
"mellow pack leader",
"electric violence",
"savage deviant",
"gruesome snake",
"smutty outburst",
"undependable locker room",
"iconic totem pole",
"spry emotion",
"psycho waste of a person",
"moody descending color",
"foolish extremity",
"caught-in-the-act jackass",
"skeletal error",
"feminine change for good",
"purebred marshmallow",
"beautiful elastic band",
"peg-legged patrolman",
"high-flying cocksucker",
"pretty background story",
"half-obedient radio beam",
"compassionate bad mood",
"nostalgic latest version",
"high-waisted sweetheart",
"nighttime villain",
"the original drunk",
"rowdy vengeance",
"trendy rat",
"dense chicken stew",
"brokenhearted druggie",
"strategic railroad worm",
"whimsical selfishness",
"wishful crime scene",
"dainty sneaky criminal",
"unfiltered manure",
"hack-and-slash laser beams",
"greedy personal credit line",
"problem-solving elastic band",
"killer mental case",
"two-dimensional pizza cutter",
"nasty haunted graveyard",
"world-renowned wrongdoing",
"disappointing pervert",
"automotive sewing-machine operator",
"tough nibblets",
"mischievous hypocrite",
"form-fitting ice cream",
"top-level disappointment",
"undead pillow",
"disobedient promise-breaker",
"savvy simpleton",
"strapping cold heart",
"shitty rough-skinned newt",
"buxom personality",
"non-alcoholic inside dog",
"drapey truth",
"friendless deer antler",
"connected mental disorder",
"mammoth kibble",
"cat-friendly reading party",
"nauseating kitty",
"ghoulishly delightful merry bells",
"skunk-proof wiener",
"emotional traitor",
"organically produced crime",
"furry blunder",
"oversized attention whore",
"dark sorry excuse",
"smart haunted graveyard",
"annual bitterness",
"sorrowful outrage",
"gangly nonbeliever",
"crummy marshmallow",
"deepest wrinkle",
"engineered apology",
"floaty problem",
"fancy pain",
"neutered temper tantrum",
"thickset terrorist",
"huggable rat",
"bat-shit crazy amish folk",
"lovable sleazeball",
"pronounced thunder legs",
"nice toast",
"practical wandering eye",
"miniature police department",
"potty-trained deception",
"solid mental case",
"passing polkdot",
"intelligent confusing situation",
"whiny thief",
"printed total joke",
"bloody indignation",
"pampered notion of love",
"embarrassing hairy legs",
"crazy cute meeting with my mom",
"loving informal request",
"flattering space emulator",
"edgy bond",
"smoky bad attitude",
"versatile drunk",
"foamy dentist’s drill",
"faster four-legged family member",
"high-agility verbal abuse",
"ice-cold lack of judgement",
"metallic manipulating ass",
"jealous bored child",
"comic divergent thinking",
"control-top light bulb",
"must-have creep"
]